# Generated by Django 3.1.7 on 2021-03-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210401_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
